# Generated by Django 3.2.5 on 2021-08-28 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_favourites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favouriets',
            new_name='Favourites',
        ),
    ]
