# Generated by Django 3.2.5 on 2021-09-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210902_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
