# Generated by Django 3.2.5 on 2021-08-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210818_1130'),
        ('checkout', '0002_auto_20210825_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLineItem',
        ),
    ]
