# Generated by Django 3.2.5 on 2021-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_default_email'),
        ('products', '0002_auto_20210804_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='profiles.UserProfile'),
        ),
    ]
